apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepl-bot
  namespace: deepl-bot
  labels:
    app: deepl-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepl-bot
  template:
    metadata:
      labels:
        app: deepl-bot
    spec:
      containers:
        - name: deepl-bot
          image: <IMAGE-NAME>
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: deepl-bot-creds
                  key: DATABASE_URL
            - name: DEEPL_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: deepl-bot-creds
                  key: DEEPL_AUTH_KEY
            - name: DISCORD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: deepl-bot-creds
                  key: DISCORD_CLIENT_ID
            - name: DISCORD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: deepl-bot-creds
                  key: DISCORD_CLIENT_SECRET
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: deepl-bot-creds
                  key: DISCORD_TOKEN
            - name: DISCORD_SERVER_ID
              valueFrom:
                configMapKeyRef:
                  name: deepl-bot-config
                  key: DISCORD_SERVER_ID
            - name: DISCORD_CHANNELS_TO_LISTEN
              valueFrom:
                configMapKeyRef:
                  name: deepl-bot-config
                  key: DISCORD_CHANNELS_TO_LISTEN
            - name: DISCORD_TRANSLATE_EMOJI_ID
              valueFrom:
                configMapKeyRef:
                  name: deepl-bot-config
                  key: DISCORD_TRANSLATE_EMOJI_ID
            - name: NODE_ENV
              value: local
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: pull-secret
